user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  size: 80
  per_page: 10
category:
  name:
    min: 3
book:
  title_max: 80
  author_max: 50
  per_page: 8
img:
  book_index: "250x350>"
  book_show: "325x475>"
session:
  remember_me: "1"
gravatar_size:
  size: 50
  size_mini: 30
follow:
  per_page: 10
per_page: 10
